apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
  namespace: spaceborscht
  labels:
    app: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3002"
        instrumentation.opentelemetry.io/inject-nodejs: "instrumentation-space"
    spec:
      containers:
      - name: telemetry
        image: cr.yandex/crpppobvo0dedl805s42/spaceborscht/telemetry:latest
        ports:
          - name: metrics-port
            containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: OTEL_SERVICE_NAME
          value: "telemetry"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        # - name: OTEL_EXPORTER_OTLP_PROTOCOL
        #   value: http/protobuf
        # - name: LOG_TRACE_ID
        #   value: "true"
        - name: OTEL_LOG_LEVEL
          value: "debug"
        - name: ERROR_RATE_DEFAULT
          value: "0.1"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
  namespace: spaceborscht
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3002"
spec:
  selector:
    app: telemetry
  ports:
    - name: metrics-port
      protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: telemetry-exporter-podmonitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: telemetry
  podMetricsEndpoints:
    - port: metrics-port
      interval: 15s