{
 "title": "dashboard_service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "services",
    "label": "service filter",
    "query": {
     "query": "label_values(http_requests_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "traces",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "services",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"spaceborscht-control\" && trace:duration > 200ms }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Availability: UP by service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (container) (up{namespace=\"spaceborscht\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All services UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{namespace=\"spaceborscht\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory working set by pod",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{namespace=\"spaceborscht\", container!=\"POD\"}\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traffic: RPS by service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (\r\n  rate(http_requests_total{service=~\"$services\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Latency: p95 by service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, service) (\r\n    rate(http_request_duration_seconds_bucket{service=~\"$services\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "avg_request",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(http_request_duration_seconds_sum{service=~\"$services\"}[$__rate_interval]))\r\n/\r\nsum by (service) (rate(http_request_duration_seconds_count{service=~\"$services\"}[$__rate_interval]))",
     "legendFormat": "{{services}}"
    }
   ]
  },
  {
   "title": "Errors: 5xx RPS by service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (\r\n  rate(http_requests_total{service=~\"$services\", status=~\"5..\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "{{services}}"
    }
   ]
  },
  {
   "title": "Error ratio (5xx / all) by service",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (service) (\r\n  rate(http_requests_total{service=~\"$services\", status=~\"5..\"}[$__rate_interval])\r\n)\r\n/\r\nsum by (service) (\r\n  rate(http_requests_total{service=~\"$services\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU usage by pod (cores)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "CPU (cores)" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"spaceborscht\", container!=\"POD\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logs: all services",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_namespace_name=\"spaceborscht\"} |= \"\""
    }
   ]
  },
  {
   "title": "Traces: spaceborscht‑contro",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"spaceborscht-control\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs: 5xx control only",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_namespace_name=\"spaceborscht\", k8s_container_name=\"$services\"} | json | level = `50`"
    }
   ]
  }
 ]
}